# ==================== TASK SELECTION ====================
# Switch between different classification tasks by changing these paths

# FOR HAIR TYPE CLASSIFICATION:
# data_dir: './data_hair_type'              # Training data location
# checkpoint_dir: './checkpoints_hair_type'  # Where to save model weights
# input_dir: './input_pictures_hair_type'    # Raw images (for prepare_data.py)

# FOR HAIR COLOR CLASSIFICATION (uncomment to use):
data_dir: './data_hair_color'
checkpoint_dir: './checkpoints_hair_color'
input_dir: './input_pictures_hair_color'

# NOTE: Classes are automatically detected from subdirectories in data_dir!
# For example:
#   data_hair_type/train/straight, wavy, curly → 3 classes: ['curly', 'straight', 'wavy']
#   data_hair_color/train/black, brown, blonde → 3 classes: ['black', 'blonde', 'brown']

# ==================== MODEL SETTINGS ====================
model_name: "convnext_tiny.fb_in22k"  # Options: deit_base_patch16_224, deit3_base_patch16_224, 
                                    #          convnext_tiny, convnext_tiny.fb_in22k
dropout: 0.2                        # Dropout rate for classifier head
img_size: 224                       # Input image size

# ==================== TRAINING SETTINGS ====================
epochs: 80                          # Total training epochs
freeze_epochs: 10                   # Epochs to freeze backbone (transfer learning)
learning_rate: 0.00005              # Learning rate (5e-5)
weight_decay: 0.01                  # Weight decay for regularization
batch_size: 24                      # Batch size
num_workers: 4                      # DataLoader workers

# ==================== DATA PREPARATION ====================
train_split: 0.7                    # 70% for training
val_split: 0.15                     # 15% for validation
test_split: 0.15                    # 15% for testing
random_seed: 42                     # Random seed for reproducibility

# ==================== DATA AUGMENTATION ====================
# Horizontal flip
aug_hflip: 0.5                      # Probability of horizontal flip

# Rotation
aug_rotate: 15                      # Max rotation degrees

# Brightness/Contrast
aug_brightness: 0.5                 # Probability of brightness/contrast adjustment

# MixUp and CutMix
use_mixup: true                     # Enable MixUp augmentation
mixup_alpha: 0.2                    # MixUp alpha parameter
use_cutmix: true                    # Enable CutMix augmentation
cutmix_alpha: 1.0                   # CutMix alpha parameter

# ==================== CLASS IMBALANCE HANDLING ====================
use_class_weights: true             # Weight loss by inverse class frequency
use_balanced_sampling: false        # Alternative: balance sampling instead of loss weighting

# ==================== TESTING ====================
test_model: "best_model.pth"        # Checkpoint filename to evaluate
use_tta: true                       # Test-Time Augmentation
tta_augmentations: 5                # Number of TTA augmentations